name: Local Build with Runner

on:
  push:
    branches: [ yepengfei/demo ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: self-hosted  # 关键！使用本地Runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14'  # 指定Node版本
        cache: 'npm'       # 缓存依赖
        
    - name: Install dependencies
      run: npm install
      
    - name: Run build
      run: npm run build   # 执行package.json中的build脚本
      
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
    - name: Deploy to local path
      run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo cp -r ./dist /var/www/html
          else
            xcopy .\dist C:\deploy /E /I /Y
          fi