name: Windows Build and Deploy - yepengfei/demo

on:
  push:
    branches: [ "yepengfei/demo" ]
  workflow_dispatch:

jobs:
  deploy-windows:
    runs-on: [self-hosted, windows]  # 仅匹配带 windows 标签的 Runner
    strategy:
      matrix:
        deploy_dir: ['C:\\yepengfei-demo']  # 矩阵定义部署路径
    
    env:
      NODE_ENV: production
      GIT_HTTP_MAX_BUFFER: 524288000
      DEPLOY_DIR: ${{ matrix.deploy_dir }}

    steps:
    # ========== 网络配置 ==========
    - name: Configure Git
      shell: powershell
      run: |
        git config --global http.sslVerify false
        git config --global http.postBuffer 1048576000
        git config --global core.longpaths true

    # ========== 代码获取 ==========
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: yepengfei/demo
        fetch-depth: 1

    # ========== 构建部分 ==========
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14'
        cache: 'npm'

    - name: Install dependencies
      shell: powershell
      run: npm ci --legacy-peer-deps

    - name: Run tests
      shell: powershell
      run: npm test

    - name: Build project
      shell: powershell
      run: npm run build

    # ========== Windows 专属部署 ==========
    - name: Create deploy directory
      shell: powershell
      run: |
        if (!(Test-Path $env:DEPLOY_DIR)) {
          New-Item -ItemType Directory -Path $env:DEPLOY_DIR
        }

    - name: Copy files
      shell: powershell
      run: |
        Copy-Item -Path ".\dist\*" -Destination $env:DEPLOY_DIR -Recurse -Force

    # ========== 验证与通知 ==========
    - name: Verify deployment
      shell: powershell
      run: |
        Write-Output "部署内容验证:"
        Get-ChildItem -Path $env:DEPLOY_DIR

    - name: Completion notice
      run: |
        echo "✅ Windows 部署完成"
        echo "本地路径: file:///$DEPLOY_DIR"
        echo "可通过资源管理器访问: $DEPLOY_DIR"