name: Build and Deploy

on:
  push:
    branches: [ "yepengfei/demo" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - os_label: linux
            deploy_dir: /var/www/yepengfei-demo
          - os_label: windows
            deploy_dir: 'C:\yepengfei-demo'
    
    env:
      NODE_ENV: production
      GIT_HTTP_MAX_BUFFER: 524288000
      DEPLOY_DIR: ${{ matrix.deploy_dir }}

    steps:
      - name: Check OS compatibility
        if: ${{ !contains(matrix.os_label, runner.label) }}
        run: |
          echo "错误：Runner 标签不匹配"
          echo "需要的标签: ${{ matrix.os_label }}"
          echo "Runner 实际标签: ${{ join(runner.labels, ',') }}"
          exit 1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare deploy directory
        run: |
          if [ "${{ matrix.os_label }}" == "windows" ]; then
            mkdir "$DEPLOY_DIR"
          else
            sudo mkdir -p "$DEPLOY_DIR"
            sudo chown -R $USER "$DEPLOY_DIR"
          fi

      - name: Deploy files
        run: |
          if [ "${{ matrix.os_label }}" == "windows" ]; then
            xcopy /E /I /Y ".\dist" "$DEPLOY_DIR\"
          else
            cp -r ./dist/* "$DEPLOY_DIR/"
          fi